"""uniqe constraint deleted from firebase_uid from otp table

Revision ID: 0c76b41991e4
Revises: 8251e3b27986
Create Date: 2024-02-12 20:27:22.520385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c76b41991e4'
down_revision = '8251e3b27986'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('otp_firebase_uid_key', 'otp', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('otp_firebase_uid_key', 'otp', ['firebase_uid'])
    # ### end Alembic commands ###
