"""is_delivered column added in orders table

Revision ID: 61e8b05c91a9
Revises: 321ce94e7b53
Create Date: 2024-02-04 18:58:55.509395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e8b05c91a9'
down_revision = '321ce94e7b53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'feedback',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('orders', sa.Column('is_delivered', sa.Boolean(), server_default=sa.text('False'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_delivered')
    op.alter_column('feedback', 'feedback',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
