"""home_page_banners table added

Revision ID: 66eabc203571
Revises: 9269d24c3d0c
Create Date: 2024-01-03 21:20:00.522244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66eabc203571'
down_revision = '9269d24c3d0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_page_banners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.Column('image_link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_page_banners')
    # ### end Alembic commands ###
