"""deleted_users table added

Revision ID: 920c3b099bc2
Revises: 2d08d7747647
Create Date: 2024-03-03 21:24:56.734250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920c3b099bc2'
down_revision = '2d08d7747647'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_users',
    sa.Column('firebase_uid', sa.String(), nullable=False),
    sa.Column('auth_type', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.PrimaryKeyConstraint('firebase_uid'),
    sa.UniqueConstraint('firebase_uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deleted_users')
    # ### end Alembic commands ###
