"""last_login column added in auth table

Revision ID: 9269d24c3d0c
Revises: 414712dc24f7
Create Date: 2023-12-17 19:02:48.685806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9269d24c3d0c'
down_revision = '414712dc24f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###
