"""index column added in home_page_banners table

Revision ID: a47cec511a80
Revises: 66eabc203571
Create Date: 2024-01-04 20:48:38.594781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a47cec511a80'
down_revision = '66eabc203571'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_page_banners', sa.Column('index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_page_banners', 'index')
    # ### end Alembic commands ###
