"""orders and bd_orders table added

Revision ID: bf0c0dd9f16b
Revises: a47cec511a80
Create Date: 2024-01-11 21:50:21.118171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0c0dd9f16b'
down_revision = 'a47cec511a80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bd_orders',
    sa.Column('bd_awb_no', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.Column('bd_ccrcrdref', sa.String(), nullable=True),
    sa.Column('bd_cluster_code', sa.String(), nullable=True),
    sa.Column('bd_destination_area', sa.String(), nullable=True),
    sa.Column('bd_destination_location', sa.String(), nullable=True),
    sa.Column('bd_is_error', sa.Boolean(), nullable=True),
    sa.Column('bd_token_number', sa.String(), nullable=True),
    sa.Column('bd_status_information', sa.String(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('bd_awb_no')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_full_address', sa.String(), nullable=False),
    sa.Column('customer_pincode', sa.String(), nullable=False),
    sa.Column('customer_address_type', sa.String(), nullable=False),
    sa.Column('customer_phone_number', sa.String(), nullable=False),
    sa.Column('customer_payment_method', sa.String(), nullable=False),
    sa.Column('order_quantity', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('actual_order_quantity', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('related_to_order_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('payable', sa.String(), nullable=False),
    sa.Column('delivery_charge', sa.String(), nullable=False),
    sa.Column('product_listed_price', sa.String(), nullable=False),
    sa.Column('bd_order_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bd_order_id'], ['bd_orders.bd_awb_no'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('bd_orders')
    # ### end Alembic commands ###
